import {
  Bus,
  Users,
  Wallet,
  Library,
  PieChart,
  Settings,
  FileText,
  BookOpen,
  UserPlus,
  Briefcase,
  LayoutGrid,
  CalendarCheck,
  LayoutDashboard,
  FileSpreadsheet,
  Package
} from 'lucide-react';

export const navItems = [
  { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER', 'ACCOUNTANT', 'STAFF', 'LIBRARIAN', 'CLERK'] },
  { name: 'Admissions', href: '/admissions', icon: UserPlus, roles: ['ADMIN', 'PRINCIPAL', 'ACCOUNTANT', 'CLERK', 'STAFF'] },
  { name: 'Students', href: '/students', icon: Users, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER', 'ACCOUNTANT', 'CLERK', 'STAFF'] },
  { name: 'ID Cards', href: '/id-cards', icon: LayoutGrid, roles: ['ADMIN', 'PRINCIPAL', 'ACCOUNTANT', 'STAFF', 'CLERK'] },
  { name: 'Attendance', href: '/attendance', icon: CalendarCheck, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER', 'STAFF'] },
  { name: 'Marks', href: '/marks', icon: FileSpreadsheet, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER'] },
  { name: 'Question Papers', href: '/question-papers', icon: FileText, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER'] },
  { name: 'Question Bank', href: '/question-bank', icon: BookOpen, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER'] },
  { name: 'Finance', href: '/finance', icon: Wallet, roles: ['ADMIN', 'PRINCIPAL', 'ACCOUNTANT'] },
  { name: 'Transport', href: '/transport', icon: Bus, roles: ['ADMIN', 'PRINCIPAL', 'ACCOUNTANT'] },
  { name: 'HR & Payroll', href: '/hr', icon: Briefcase, roles: ['ADMIN', 'PRINCIPAL', 'ACCOUNTANT', 'TEACHER', 'STAFF', 'LIBRARIAN', 'CLERK', 'SECURITY', 'CLEANER'] },
  { name: 'Library', href: '/library', icon: Library, roles: ['ADMIN', 'PRINCIPAL', 'LIBRARIAN'] },
  { name: 'Inventory', href: '/inventory', icon: Package, roles: ['ADMIN', 'PRINCIPAL', 'ACCOUNTANT', 'STAFF'] },
  { name: 'Classes', href: '/classes', icon: LayoutGrid, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER'] },
  { name: 'Reports', href: '/reports', icon: PieChart, roles: ['ADMIN', 'PRINCIPAL', 'TEACHER', 'ACCOUNTANT'] },
  { name: 'Settings', href: '/settings', icon: Settings, roles: ['ADMIN', 'PRINCIPAL'] },
  { name: 'Audit Logs', href: '/audit', icon: LayoutDashboard, roles: ['ADMIN'] },
];
